### ISSUE TITLE
データモデルを作成する

### ISSUE THREAD

**Issue by suzukikeita1** [suzukikeita1/intern-suzuki_drive-meister#13]
## 概要 (Summary):
問題データ、ユーザーデータのER図を作成する
ER図をもとにDBにテーブルを作成する
## 誰が使うか (For whom):
開発者
## 何のために or どのように実装するか (For what):
システムに必要なデータを定義するため
## 達成目標:
システムに必要なデータが抜けもれなく定義されていること

**Comment by k-hayashi-dott** [comment]
- Cloud Datastore ってなんだろうを調べる
- - 必要なテーブルを定義する
  - クイズ、復習
- そのテーブルに必要な項目を定義する
- 項目名（論理名と物理名）を定義する
- 項目に対する型を定義する
- 例
https://docs.google.com/spreadsheets/d/1qNmGOVKAGvx9ePHEZG12vbMstlnwUzeEBCmETLXEBDE/edit?gid=0#gid=0
